'use client'

import { MarketingHero, FeatureSection, HowItWorksSection, MarketingCTA } from '@/components/seo/marketing-page-sections'
import { CalendarAIAssistantFeatureMockup, InterviewScheduleFeatureMockup } from '@/components/seo/feature-mockups'

export function CalendarAIAssistantContent() {
  return (
    <>
      <MarketingHero
        badge="Calendar AI Assistant"
        title="Your AI-powered interview scheduler"
        subtitle="Chat with an AI that manages your interview calendar — schedule, reschedule, and prepare for interviews through conversation."
        videoSrc=""
      />

      <section className="px-6 py-16 bg-white">
        <div className="max-w-6xl mx-auto space-y-20 lg:space-y-28">
          <FeatureSection
            title="Schedule interviews through conversation"
            description="Tell the AI when you're available and it handles the rest. Add interviews, set reminders, and manage your schedule — all through natural conversation instead of clicking through forms."
            bullets={[
              'Add interviews by describing them in plain language',
              'Set reminders and preparation time before each interview',
              'Manage multiple interviews across different time zones',
              'Monthly, weekly, and daily calendar views with color-coded events',
              'Smart scheduling suggestions to avoid conflicts and back-to-back interviews',
            ]}
            mockup={<CalendarAIAssistantFeatureMockup />}
          />

          <FeatureSection
            title="Interview preparation and reminders"
            description="The AI reminds you about upcoming interviews and helps you prepare. Get company research summaries, common interview questions for the role, and a checklist of materials to bring — all generated automatically."
            bullets={[
              'Automated reminders before each interview',
              'Company and role research summaries generated by AI',
              'Suggested questions to ask based on the job description',
              'Preparation checklist customized to the interview type',
              'Blocks preparation time before each interview automatically',
            ]}
            mockup={<InterviewScheduleFeatureMockup />}
            reverse
          />
        </div>
      </section>

      <HowItWorksSection
        steps={[
          { title: 'Tell the AI about your interview', description: 'Share the company, role, date, and time — the AI adds it to your calendar.' },
          { title: 'Prepare with AI help', description: 'Get company research, role-specific questions, and prep reminders before each interview.' },
          { title: 'Stay on track', description: 'View your full schedule, reschedule when needed, and never miss an interview.' },
        ]}
      />

      <MarketingCTA
        title="Never miss another interview"
        subtitle="Let AI manage your interview calendar, send reminders, and help you prepare — completely free."
      />
    </>
  )
}
