import type { CVTheme, ThemeCategory, Industry, SidebarStyle } from './types/cv'

export interface ThemePreset extends CVTheme {
  id: string
  name: string
  category: ThemeCategory
  industry?: Industry
  description: string
}

// Industry-Focused Themes (10)
const industryThemes: ThemePreset[] = [
  {
    id: 'tech-modern',
    name: 'Tech Modern',
    category: 'industry',
    industry: 'tech',
    description: 'Clean tech startup feel with modern aesthetics',
    colors: {
      primary: '#1A73E8',
      accent: '#34A853',
      text: '#0F172A',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'finance',
    name: 'Finance',
    category: 'industry',
    industry: 'finance',
    description: 'Conservative banking style, trustworthy',
    colors: {
      primary: '#1E3A5F',
      accent: '#C9A227',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'circle',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    category: 'industry',
    industry: 'healthcare',
    description: 'Clinical, clean, and trustworthy',
    colors: {
      primary: '#0B7285',
      accent: '#0CA678',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'academic',
    skillsStyle: 'grid',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'legal',
    name: 'Legal',
    category: 'industry',
    industry: 'legal',
    description: 'Traditional, authoritative presence',
    colors: {
      primary: '#1C1917',
      accent: '#78350F',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#57534E',
    },
    fonts: { heading: 'Playfair Display', body: 'Merriweather' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'academia',
    name: 'Academia',
    category: 'industry',
    industry: 'academia',
    description: 'Academic and research focused',
    colors: {
      primary: '#5B21B6',
      accent: '#1D4ED8',
      text: '#1E1B4B',
      background: '#FFFFFF',
      secondary: '#6366F1',
    },
    fonts: { heading: 'Merriweather', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: true,
  },
  {
    id: 'creative-agency',
    name: 'Creative Agency',
    category: 'industry',
    industry: 'creative',
    description: 'Bold and artistic expression',
    colors: {
      primary: '#BE185D',
      accent: '#D97706',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#8B5CF6',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'engineering',
    name: 'Engineering',
    category: 'industry',
    industry: 'engineering',
    description: 'Technical, precise, and clean',
    colors: {
      primary: '#2563EB',
      accent: '#0EA5E9',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'marketing',
    name: 'Marketing',
    category: 'industry',
    industry: 'marketing',
    description: 'Dynamic and engaging',
    colors: {
      primary: '#C2410C',
      accent: '#0891B2',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#71717A',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'consulting',
    name: 'Consulting',
    category: 'industry',
    industry: 'consulting',
    description: 'Premium and polished',
    colors: {
      primary: '#0F172A',
      accent: '#3B82F6',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'retail',
    name: 'Retail',
    category: 'industry',
    industry: 'retail',
    description: 'Friendly and approachable',
    colors: {
      primary: '#15803D',
      accent: '#CA8A04',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
]

// Style-Focused Themes (10)
const styleThemes: ThemePreset[] = [
  {
    id: 'bold-modern',
    name: 'Bold Modern',
    category: 'style',
    description: 'Strong typography, high contrast',
    colors: {
      primary: '#0F0F0F',
      accent: '#B91C1C',
      text: '#000000',
      background: '#FFFFFF',
      secondary: '#666666',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'square',
    photoStyle: 'square',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'soft-pastel',
    name: 'Soft Pastel',
    category: 'style',
    description: 'Gentle colors, rounded shapes',
    colors: {
      primary: '#7C3AED',
      accent: '#DB2777',
      text: '#3F3F46',
      background: '#FAFAFA',
      secondary: '#A1A1AA',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'cards',
    educationStyle: 'cards',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'none',
    sectionBorder: 'card',
    bulletStyle: 'circle',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    category: 'style',
    description: 'Black, white, and gray only',
    colors: {
      primary: '#18181B',
      accent: '#52525B',
      text: '#27272A',
      background: '#FFFFFF',
      secondary: '#71717A',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    category: 'style',
    description: 'Dark background variant',
    colors: {
      primary: '#60A5FA',
      accent: '#34D399',
      text: '#F4F4F5',
      background: '#18181B',
      secondary: '#A1A1AA',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'gradient-accent',
    name: 'Gradient Accent',
    category: 'style',
    description: 'Gradient highlights throughout',
    colors: {
      primary: '#6D28D9',
      accent: '#BE185D',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6366F1',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'gradient',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'neon',
    name: 'Neon',
    category: 'style',
    description: 'Bright accent colors that pop',
    colors: {
      primary: '#0E7490',
      accent: '#BE185D',
      text: '#0F172A',
      background: '#FFFFFF',
      secondary: '#22D3EE',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'cards',
    educationStyle: 'cards',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'vintage',
    name: 'Vintage',
    category: 'style',
    description: 'Retro classic feel',
    colors: {
      primary: '#78350F',
      accent: '#B45309',
      text: '#451A03',
      background: '#FEF3C7',
      secondary: '#92400E',
    },
    fonts: { heading: 'Playfair Display', body: 'Merriweather' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'quoted',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'swiss',
    name: 'Swiss',
    category: 'style',
    description: 'Swiss design principles - clean grid',
    colors: {
      primary: '#EF4444',
      accent: '#000000',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#71717A',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'square',
    photoStyle: 'none',
    dateFormat: 'numeric',
    showHeaderIcons: false,
  },
  {
    id: 'japanese-minimal',
    name: 'Japanese Minimal',
    category: 'style',
    description: 'Zen-inspired, whitespace-heavy',
    colors: {
      primary: '#1C1917',
      accent: '#DC2626',
      text: '#292524',
      background: '#FAFAF9',
      secondary: '#78716C',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'year-only',
    showHeaderIcons: false,
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    category: 'style',
    description: 'Raw, stark, impactful design',
    colors: {
      primary: '#000000',
      accent: '#FACC15',
      text: '#000000',
      background: '#FFFFFF',
      secondary: '#737373',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'compact',
    headerStyle: 'left-aligned',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'tags-outlined',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'accent-left',
    bulletStyle: 'square',
    photoStyle: 'square',
    dateFormat: 'numeric',
    showHeaderIcons: false,
  },
]

// Specialty Themes (5+)
const specialtyThemes: ThemePreset[] = [
  {
    id: 'one-page',
    name: 'One Page',
    category: 'specialty',
    description: 'Optimized for single page',
    colors: {
      primary: '#374151',
      accent: '#6B7280',
      text: '#111827',
      background: '#FFFFFF',
      secondary: '#9CA3AF',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'compact',
    spacing: 'compact',
    headerStyle: 'compact',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'infographic',
    name: 'Infographic',
    category: 'specialty',
    description: 'Visual and chart emphasis',
    colors: {
      primary: '#3B82F6',
      accent: '#10B981',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6366F1',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'timeline',
    educationStyle: 'cards',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'timeline-focus',
    name: 'Timeline Focus',
    category: 'specialty',
    description: 'Timeline-centric design',
    colors: {
      primary: '#7C3AED',
      accent: '#A78BFA',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#8B5CF6',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'timeline',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'timeline',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'circle',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'photo-resume',
    name: 'Photo Resume',
    category: 'specialty',
    description: 'Large photo, visual emphasis',
    colors: {
      primary: '#0F172A',
      accent: '#38BDF8',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'federal',
    name: 'Federal',
    category: 'specialty',
    industry: 'government',
    description: 'Government and public sector',
    colors: {
      primary: '#1E3A8A',
      accent: '#1D4ED8',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'ats-optimized',
    name: 'ATS Optimized',
    category: 'specialty',
    description: 'Maximum ATS compatibility',
    colors: {
      primary: '#000000',
      accent: '#000000',
      text: '#000000',
      background: '#FFFFFF',
    },
    fonts: { heading: 'Arial', body: 'Arial' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
]

// Professional Color Themes (5 new premium templates)
const professionalThemes: ThemePreset[] = [
  {
    id: 'executive-navy',
    name: 'Executive Navy',
    category: 'style',
    industry: 'consulting',
    description: 'Premium dark navy with gold accents for C-level and consulting',
    colors: {
      primary: '#0F1729',
      accent: '#B8860B',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#475569',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'corporate-slate',
    name: 'Corporate Slate',
    category: 'style',
    industry: 'finance',
    description: 'Sophisticated slate gray for finance and banking',
    colors: {
      primary: '#334155',
      accent: '#6B82A6',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'classic-professional',
    name: 'Classic Professional',
    category: 'style',
    industry: 'legal',
    description: 'Traditional dark gray with burgundy for legal and formal',
    colors: {
      primary: '#1F2937',
      accent: '#722F37',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Playfair Display', body: 'Merriweather' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'modern-neutral',
    name: 'Modern Neutral',
    category: 'style',
    industry: 'general',
    description: 'Versatile neutral tones for any industry',
    colors: {
      primary: '#5C5C5C',
      accent: '#7D8471',
      text: '#333333',
      background: '#FFFFFF',
      secondary: '#9CA3AF',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'tech-minimal',
    name: 'Tech Minimal',
    category: 'style',
    industry: 'tech',
    description: 'Clean black and gray for tech and startups',
    colors: {
      primary: '#171717',
      accent: '#9CA3AF',
      text: '#171717',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
]

// New Industry Templates (20)
const newIndustryThemes: ThemePreset[] = [
  {
    id: 'data-science',
    name: 'Data Science',
    category: 'industry',
    industry: 'tech',
    description: 'Analytical and data-driven aesthetic',
    colors: {
      primary: '#1E40AF',
      accent: '#059669',
      text: '#0F172A',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'academic',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    category: 'industry',
    industry: 'tech',
    description: 'Secure, dark-toned tech feel',
    colors: {
      primary: '#0F172A',
      accent: '#22C55E',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#475569',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'compact',
    skillsStyle: 'tags-outlined',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'square',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'product-manager',
    name: 'Product Manager',
    category: 'industry',
    industry: 'tech',
    description: 'Strategic and cross-functional focus',
    colors: {
      primary: '#4338CA',
      accent: '#0891B2',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'top-banner',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'nonprofit',
    name: 'Nonprofit',
    category: 'industry',
    industry: 'general',
    description: 'Mission-driven and community focused',
    colors: {
      primary: '#065F46',
      accent: '#B45309',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'education-k12',
    name: 'Education K-12',
    category: 'industry',
    industry: 'academia',
    description: 'Warm and approachable for educators',
    colors: {
      primary: '#1D4ED8',
      accent: '#DC2626',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'sidebar-right',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'classic',
    educationStyle: 'academic',
    skillsStyle: 'pills',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'real-estate',
    name: 'Real Estate',
    category: 'industry',
    industry: 'consulting',
    description: 'Polished for property professionals',
    colors: {
      primary: '#1C1917',
      accent: '#B8860B',
      text: '#292524',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'detailed',
    educationStyle: 'compact',
    skillsStyle: 'grid',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'hospitality',
    name: 'Hospitality',
    category: 'industry',
    industry: 'retail',
    description: 'Warm and service-oriented',
    colors: {
      primary: '#7C2D12',
      accent: '#B45309',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'pills',
    summaryStyle: 'plain',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'media-journalism',
    name: 'Media & Journalism',
    category: 'industry',
    industry: 'creative',
    description: 'Editorial layout for media professionals',
    colors: {
      primary: '#0F172A',
      accent: '#B91C1C',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'magazine',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'quoted',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'architecture',
    name: 'Architecture',
    category: 'industry',
    industry: 'engineering',
    description: 'Clean lines for design-build professionals',
    colors: {
      primary: '#1C1917',
      accent: '#64748B',
      text: '#292524',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'sidebar-right',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'square',
    dateFormat: 'year-only',
    showHeaderIcons: false,
  },
  {
    id: 'supply-chain',
    name: 'Supply Chain',
    category: 'industry',
    industry: 'engineering',
    description: 'Structured for logistics and operations',
    colors: {
      primary: '#1E3A8A',
      accent: '#0E7490',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'hr-recruiter',
    name: 'HR & Recruiting',
    category: 'industry',
    industry: 'consulting',
    description: 'People-focused and approachable',
    colors: {
      primary: '#7C3AED',
      accent: '#0891B2',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'pharma-biotech',
    name: 'Pharma & Biotech',
    category: 'industry',
    industry: 'healthcare',
    description: 'Scientific precision for life sciences',
    colors: {
      primary: '#0B4F6C',
      accent: '#047857',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'timeline',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'timeline',
    educationStyle: 'academic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: true,
  },
  {
    id: 'startup-founder',
    name: 'Startup Founder',
    category: 'industry',
    industry: 'tech',
    description: 'Bold and entrepreneurial',
    colors: {
      primary: '#0F0F0F',
      accent: '#6D28D9',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#71717A',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'top-banner',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'insurance',
    name: 'Insurance',
    category: 'industry',
    industry: 'finance',
    description: 'Trustworthy and detail-oriented',
    colors: {
      primary: '#1E3A5F',
      accent: '#4338CA',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'logistics',
    name: 'Logistics',
    category: 'industry',
    industry: 'engineering',
    description: 'Efficient and operations-focused',
    colors: {
      primary: '#334155',
      accent: '#0E7490',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'compact',
    spacing: 'compact',
    headerStyle: 'compact',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'social-work',
    name: 'Social Work',
    category: 'industry',
    industry: 'healthcare',
    description: 'Compassionate and community-oriented',
    colors: {
      primary: '#4338CA',
      accent: '#047857',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'sidebar-right',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'academic',
    skillsStyle: 'pills',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'sports-fitness',
    name: 'Sports & Fitness',
    category: 'industry',
    industry: 'general',
    description: 'Energetic and performance-driven',
    colors: {
      primary: '#0F172A',
      accent: '#B91C1C',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'top-banner',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'bars',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'square',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'environmental',
    name: 'Environmental',
    category: 'industry',
    industry: 'engineering',
    description: 'Green and sustainability focused',
    colors: {
      primary: '#14532D',
      accent: '#0E7490',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'academic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'automotive',
    name: 'Automotive',
    category: 'industry',
    industry: 'engineering',
    description: 'Industrial strength for auto professionals',
    colors: {
      primary: '#1C1917',
      accent: '#B91C1C',
      text: '#292524',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'compact',
    skillsStyle: 'tags-outlined',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'accent-left',
    bulletStyle: 'square',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'telecom',
    name: 'Telecommunications',
    category: 'industry',
    industry: 'tech',
    description: 'Connected and infrastructure focused',
    colors: {
      primary: '#1E3A8A',
      accent: '#0E7490',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
]

// New Style Templates (28)
const newStyleThemes: ThemePreset[] = [
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    category: 'style',
    description: 'Cool coastal tones, calming feel',
    colors: {
      primary: '#0C4A6E',
      accent: '#155E75',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'circle',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    category: 'style',
    description: 'Deep natural greens, grounded feel',
    colors: {
      primary: '#14532D',
      accent: '#3F6212',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Merriweather', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'sunset-warm',
    name: 'Sunset Warm',
    category: 'style',
    description: 'Warm earth tones with amber accents',
    colors: {
      primary: '#7C2D12',
      accent: '#B45309',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'top-banner',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'arctic-frost',
    name: 'Arctic Frost',
    category: 'style',
    description: 'Cool steel blues, crisp and clean',
    colors: {
      primary: '#1E3A5F',
      accent: '#64748B',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#94A3B8',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'sidebar-right',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'dash',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'midnight-blue',
    name: 'Midnight Blue',
    category: 'style',
    description: 'Deep navy tones, sophisticated',
    colors: {
      primary: '#0F1729',
      accent: '#1E40AF',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#475569',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    category: 'style',
    description: 'Rich rose with gold highlights',
    colors: {
      primary: '#881337',
      accent: '#B8860B',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'quoted',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'circle',
    photoStyle: 'circle',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    category: 'style',
    description: 'Dark charcoal, understated elegance',
    colors: {
      primary: '#1C1917',
      accent: '#78716C',
      text: '#292524',
      background: '#FFFFFF',
      secondary: '#A8A29E',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'lavender',
    name: 'Lavender',
    category: 'style',
    description: 'Soft purple tones, gentle presence',
    colors: {
      primary: '#4C1D95',
      accent: '#7C3AED',
      text: '#1E1B4B',
      background: '#FFFFFF',
      secondary: '#8B5CF6',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'sidebar-right',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'cards',
    educationStyle: 'cards',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'none',
    sectionBorder: 'card',
    bulletStyle: 'circle',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'emerald',
    name: 'Emerald',
    category: 'style',
    description: 'Rich green, professional polish',
    colors: {
      primary: '#064E3B',
      accent: '#059669',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    category: 'style',
    description: 'Warm coral with teal contrast',
    colors: {
      primary: '#9A3412',
      accent: '#0E7490',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'top-banner',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'slate-modern',
    name: 'Slate Modern',
    category: 'style',
    description: 'Modern slate gray, clean lines',
    colors: {
      primary: '#334155',
      accent: '#475569',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#94A3B8',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'tags-outlined',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'burgundy-classic',
    name: 'Burgundy Classic',
    category: 'style',
    description: 'Deep burgundy, timeless formality',
    colors: {
      primary: '#4A0404',
      accent: '#7C2D12',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Playfair Display', body: 'Merriweather' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'quoted',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'dusty-rose',
    name: 'Dusty Rose',
    category: 'style',
    description: 'Muted rose tones, soft elegance',
    colors: {
      primary: '#831843',
      accent: '#9D174D',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'sidebar-right',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'circle',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'steel-blue',
    name: 'Steel Blue',
    category: 'style',
    description: 'Industrial steel blue, strong presence',
    colors: {
      primary: '#1E3A5F',
      accent: '#3B82F6',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'olive-earth',
    name: 'Olive Earth',
    category: 'style',
    description: 'Earthy olive greens, organic feel',
    colors: {
      primary: '#3F3F00',
      accent: '#65A30D',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'Merriweather', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'nordic',
    name: 'Nordic',
    category: 'style',
    description: 'Scandinavian simplicity, muted tones',
    colors: {
      primary: '#1E293B',
      accent: '#64748B',
      text: '#334155',
      background: '#FFFFFF',
      secondary: '#94A3B8',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'year-only',
    showHeaderIcons: false,
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    category: 'style',
    description: 'Warm terracotta earth tones',
    colors: {
      primary: '#7C2D12',
      accent: '#C2410C',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'top-banner',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'ink-wash',
    name: 'Ink Wash',
    category: 'style',
    description: 'Ink-on-paper monochromatic',
    colors: {
      primary: '#0F172A',
      accent: '#475569',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#94A3B8',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'quoted',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'copper-accent',
    name: 'Copper Accent',
    category: 'style',
    description: 'Dark base with warm copper pops',
    colors: {
      primary: '#1C1917',
      accent: '#B45309',
      text: '#292524',
      background: '#FFFFFF',
      secondary: '#78716C',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'sidebar-right',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'sage-minimal',
    name: 'Sage Minimal',
    category: 'style',
    description: 'Sage green with minimal styling',
    colors: {
      primary: '#374151',
      accent: '#4D7C0F',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#9CA3AF',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'plum',
    name: 'Plum',
    category: 'style',
    description: 'Rich plum purples, distinctive',
    colors: {
      primary: '#581C87',
      accent: '#7E22CE',
      text: '#1E1B4B',
      background: '#FFFFFF',
      secondary: '#8B5CF6',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'sand-dune',
    name: 'Sand Dune',
    category: 'style',
    description: 'Desert-inspired warm neutrals',
    colors: {
      primary: '#78350F',
      accent: '#A16207',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#92400E',
    },
    fonts: { heading: 'Merriweather', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'electric-indigo',
    name: 'Electric Indigo',
    category: 'style',
    description: 'Deep indigo with electric accents',
    colors: {
      primary: '#312E81',
      accent: '#4338CA',
      text: '#1E1B4B',
      background: '#FFFFFF',
      secondary: '#6366F1',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'top-banner',
    spacing: 'normal',
    headerStyle: 'gradient',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'warm-gray',
    name: 'Warm Gray',
    category: 'style',
    description: 'Warm stone grays, understated',
    colors: {
      primary: '#44403C',
      accent: '#78716C',
      text: '#292524',
      background: '#FFFFFF',
      secondary: '#A8A29E',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'teal-professional',
    name: 'Teal Professional',
    category: 'style',
    description: 'Professional teal, modern corporate',
    colors: {
      primary: '#134E4A',
      accent: '#0D9488',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'boxed',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'two-tone',
    name: 'Two Tone',
    category: 'style',
    description: 'Bold two-color contrast design',
    colors: {
      primary: '#0F172A',
      accent: '#B91C1C',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'sidebar-right',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'tags-outlined',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'accent-left',
    bulletStyle: 'square',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'paper-white',
    name: 'Paper White',
    category: 'style',
    description: 'Ultra-clean, minimal on white',
    colors: {
      primary: '#1F2937',
      accent: '#6B7280',
      text: '#374151',
      background: '#FFFFFF',
      secondary: '#9CA3AF',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'dark-elegant',
    name: 'Dark Elegant',
    category: 'style',
    description: 'Dark theme with gold luxury accents',
    colors: {
      primary: '#171717',
      accent: '#B8860B',
      text: '#F4F4F5',
      background: '#18181B',
      secondary: '#A1A1AA',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'square',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
]

// New Specialty Templates (20)
const newSpecialtyThemes: ThemePreset[] = [
  {
    id: 'career-changer',
    name: 'Career Changer',
    category: 'specialty',
    description: 'Skills-first layout for career transitions',
    colors: {
      primary: '#4338CA',
      accent: '#0891B2',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'first-job',
    name: 'First Job',
    category: 'specialty',
    description: 'Entry-level with education focus',
    colors: {
      primary: '#1D4ED8',
      accent: '#059669',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'academic',
    skillsStyle: 'pills',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'freelancer',
    name: 'Freelancer',
    category: 'specialty',
    description: 'Portfolio-style for independent contractors',
    colors: {
      primary: '#7C3AED',
      accent: '#DB2777',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#71717A',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'senior-executive',
    name: 'Senior Executive',
    category: 'specialty',
    description: 'C-suite with board experience emphasis',
    colors: {
      primary: '#0F172A',
      accent: '#B8860B',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#475569',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'academic-cv',
    name: 'Academic CV',
    category: 'specialty',
    industry: 'academia',
    description: 'Long-form academic with publications',
    colors: {
      primary: '#5B21B6',
      accent: '#1D4ED8',
      text: '#1E1B4B',
      background: '#FFFFFF',
      secondary: '#6366F1',
    },
    fonts: { heading: 'Merriweather', body: 'Inter' },
    layout: 'timeline',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'timeline',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: true,
  },
  {
    id: 'creative-portfolio',
    name: 'Creative Portfolio',
    category: 'specialty',
    industry: 'creative',
    description: 'Visual portfolio layout for creatives',
    colors: {
      primary: '#BE185D',
      accent: '#6D28D9',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#8B5CF6',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'magazine',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'remote-worker',
    name: 'Remote Worker',
    category: 'specialty',
    description: 'Highlights remote and distributed skills',
    colors: {
      primary: '#0E7490',
      accent: '#6D28D9',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'sidebar-right',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'bars',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'military-transition',
    name: 'Military Transition',
    category: 'specialty',
    industry: 'government',
    description: 'Military to civilian career transition',
    colors: {
      primary: '#1E3A8A',
      accent: '#1D4ED8',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'intern',
    name: 'Intern',
    category: 'specialty',
    description: 'Student and intern focused, compact',
    colors: {
      primary: '#2563EB',
      accent: '#0891B2',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'compact',
    spacing: 'compact',
    headerStyle: 'compact',
    experienceStyle: 'compact',
    educationStyle: 'academic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'bilingual',
    name: 'Bilingual',
    category: 'specialty',
    description: 'Dual-language emphasis layout',
    colors: {
      primary: '#4338CA',
      accent: '#059669',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'volunteer-focus',
    name: 'Volunteer Focus',
    category: 'specialty',
    description: 'Nonprofit and volunteer experience heavy',
    colors: {
      primary: '#065F46',
      accent: '#B45309',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'technical-writer',
    name: 'Technical Writer',
    category: 'specialty',
    industry: 'tech',
    description: 'Documentation and writing focused',
    colors: {
      primary: '#1E293B',
      accent: '#475569',
      text: '#334155',
      background: '#FFFFFF',
      secondary: '#94A3B8',
    },
    fonts: { heading: 'Merriweather', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'quoted',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'sales-achiever',
    name: 'Sales Achiever',
    category: 'specialty',
    industry: 'marketing',
    description: 'Metrics and achievement focused layout',
    colors: {
      primary: '#0F172A',
      accent: '#B91C1C',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'top-banner',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'detailed',
    educationStyle: 'compact',
    skillsStyle: 'bars',
    languagesStyle: 'inline',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'project-manager',
    name: 'Project Manager',
    category: 'specialty',
    industry: 'consulting',
    description: 'PM methodologies and certifications',
    colors: {
      primary: '#334155',
      accent: '#0891B2',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'sidebar-right',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'ux-designer',
    name: 'UX Designer',
    category: 'specialty',
    industry: 'creative',
    description: 'Design-focused with portfolio emphasis',
    colors: {
      primary: '#BE185D',
      accent: '#7C3AED',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#71717A',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'magazine',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'teacher',
    name: 'Teacher',
    category: 'specialty',
    industry: 'academia',
    description: 'Education professional with certifications',
    colors: {
      primary: '#1D4ED8',
      accent: '#DC2626',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'classic',
    educationStyle: 'academic',
    skillsStyle: 'pills',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'researcher',
    name: 'Researcher',
    category: 'specialty',
    industry: 'academia',
    description: 'Research publication focused timeline',
    colors: {
      primary: '#5B21B6',
      accent: '#0E7490',
      text: '#1E1B4B',
      background: '#FFFFFF',
      secondary: '#6366F1',
    },
    fonts: { heading: 'Merriweather', body: 'Inter' },
    layout: 'timeline',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'timeline',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: true,
  },
  {
    id: 'minimalist-ats',
    name: 'Minimalist ATS',
    category: 'specialty',
    description: 'Ultra-clean ATS-friendly format',
    colors: {
      primary: '#374151',
      accent: '#6B7280',
      text: '#111827',
      background: '#FFFFFF',
      secondary: '#9CA3AF',
    },
    fonts: { heading: 'Arial', body: 'Arial' },
    layout: 'compact',
    spacing: 'compact',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'two-page-exec',
    name: 'Two Page Executive',
    category: 'specialty',
    description: 'Detailed executive format for senior roles',
    colors: {
      primary: '#0F1729',
      accent: '#B8860B',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#475569',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'circle',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'visual-timeline',
    name: 'Visual Timeline',
    category: 'specialty',
    description: 'Timeline-heavy chronological design',
    colors: {
      primary: '#7C3AED',
      accent: '#0891B2',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#8B5CF6',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'timeline',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'timeline',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'circle',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'data-analyst',
    name: 'Data Analyst',
    category: 'specialty',
    industry: 'tech',
    description: 'Numbers-driven layout for analysts',
    colors: {
      primary: '#1E40AF',
      accent: '#0E7490',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'sidebar-right',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
]

// Combined theme presets
export const themePresets: ThemePreset[] = [
  ...industryThemes,
  ...styleThemes,
  ...specialtyThemes,
  ...professionalThemes,
  ...newIndustryThemes,
  ...newStyleThemes,
  ...newSpecialtyThemes,
]

// Legacy predefined themes (backwards compatible)
export const predefinedThemes: Record<string, CVTheme> = {
  ats: themePresets.find(t => t.id === 'ats-optimized')!,
  professional: {
    colors: {
      primary: '#3B82F6',
      accent: '#10B981',
      text: '#1F2937',
      background: '#FFFFFF',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  creative: {
    colors: {
      primary: '#8B5CF6',
      accent: '#EC4899',
      text: '#18181B',
      background: '#FFFFFF',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'cards',
    educationStyle: 'cards',
    skillsStyle: 'pills',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  minimal: {
    colors: {
      primary: '#374151',
      accent: '#6B7280',
      text: '#111827',
      background: '#FFFFFF',
    },
    fonts: { heading: 'Geist', body: 'Geist' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  elegant: {
    colors: {
      primary: '#1E40AF',
      accent: '#059669',
      text: '#0F172A',
      background: '#FFFFFF',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'boxed',
    sectionDivider: 'dotted',
    sectionBorder: 'subtle',
    bulletStyle: 'circle',
    photoStyle: 'circle',
    dateFormat: 'full',
    showHeaderIcons: true,
  },
  executive: {
    colors: {
      primary: '#0F172A',
      accent: '#D97706',
      text: '#1E293B',
      background: '#FFFFFF',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'square',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
}

// Font options
export const fontOptions = [
  'Arial',
  'Calibri',
  'DM Sans',
  'Geist',
  'Inter',
  'Roboto',
  'Open Sans',
  'Lato',
  'Merriweather',
  'Playfair Display',
  'Montserrat',
  'Poppins',
  'Source Sans Pro',
  'Nunito',
  'Work Sans',
]

// Layout options with metadata
export const layoutOptions: Array<{
  value: CVTheme['layout']
  label: string
  description: string
}> = [
  { value: 'classic', label: 'Classic', description: 'Traditional single-column layout' },
  { value: 'sidebar-left', label: 'Sidebar Left', description: 'Left sidebar for skills/contact' },
  { value: 'sidebar-right', label: 'Sidebar Right', description: 'Right sidebar for skills/contact' },
  { value: 'top-banner', label: 'Top Banner', description: 'Full-width header banner' },
  { value: 'compact', label: 'Compact', description: 'Dense, single-page optimized' },
  { value: 'timeline', label: 'Timeline', description: 'Vertical timeline layout' },
  { value: 'magazine', label: 'Magazine', description: 'Multi-column editorial style' },
]

// Helper functions
export function getThemesByCategory(category: ThemeCategory): ThemePreset[] {
  return themePresets.filter(t => t.category === category)
}

export function getThemesByIndustry(industry: Industry): ThemePreset[] {
  return themePresets.filter(t => t.industry === industry)
}

export function getThemeById(id: string): ThemePreset | undefined {
  return themePresets.find(t => t.id === id)
}

export function suggestThemeForIndustry(industry: Industry): ThemePreset | undefined {
  return themePresets.find(t => t.industry === industry) || themePresets.find(t => t.id === 'tech-modern')
}

// Industry detection keywords for AI auto-suggest
export const industryKeywords: Record<Industry, string[]> = {
  tech: ['software', 'developer', 'engineer', 'programming', 'tech', 'startup', 'web', 'mobile', 'frontend', 'backend', 'fullstack', 'devops', 'cloud', 'ai', 'machine learning', 'data science'],
  finance: ['finance', 'banking', 'investment', 'accounting', 'financial', 'analyst', 'trader', 'portfolio', 'wealth', 'asset'],
  healthcare: ['healthcare', 'medical', 'nurse', 'doctor', 'clinical', 'hospital', 'patient', 'pharmaceutical', 'health'],
  legal: ['legal', 'lawyer', 'attorney', 'law', 'paralegal', 'counsel', 'litigation', 'compliance'],
  academia: ['professor', 'research', 'academic', 'university', 'phd', 'teaching', 'lecturer', 'scholar', 'postdoc'],
  creative: ['design', 'creative', 'art', 'graphic', 'ux', 'ui', 'animation', 'video', 'photography', 'illustration'],
  engineering: ['mechanical', 'electrical', 'civil', 'structural', 'manufacturing', 'industrial', 'automotive'],
  marketing: ['marketing', 'brand', 'digital marketing', 'seo', 'content', 'social media', 'advertising', 'pr', 'communications'],
  consulting: ['consultant', 'consulting', 'strategy', 'management', 'advisory', 'business'],
  retail: ['retail', 'sales', 'store', 'customer service', 'merchandising', 'e-commerce', 'shop'],
  government: ['government', 'federal', 'state', 'public sector', 'civil service', 'policy', 'administration'],
  general: [],
}

// Quick color presets for theme customizer (used in ColorsTab)
export const colorPresets = {
  primary: [
    '#1D4ED8', '#5B21B6', '#047857', '#B91C1C', '#C2410C', '#0B7285', '#4338CA', '#9D174D',
    '#0F1729', '#334155', '#1F2937', '#5C5C5C', '#171717', '#1E3A5F',
  ],
  accent: [
    '#2563EB', '#6D28D9', '#059669', '#DC2626', '#D97706', '#0891B2', '#4F46E5', '#BE185D',
    '#B8860B', '#6B82A6', '#722F37', '#7D8471', '#9CA3AF', '#C9A227',
  ],
  text: ['#0f172a', '#1e293b', '#334155', '#374151', '#1f2937', '#111827'],
  background: ['#ffffff', '#f8fafc', '#f1f5f9', '#fefce8', '#fef2f2', '#f0fdf4'],
}

export function detectIndustryFromText(text: string): Industry {
  const lowerText = text.toLowerCase()
  let bestMatch: Industry = 'general'
  let maxScore = 0

  for (const [industry, keywords] of Object.entries(industryKeywords)) {
    if (industry === 'general') continue
    const score = keywords.filter(kw => lowerText.includes(kw)).length
    if (score > maxScore) {
      maxScore = score
      bestMatch = industry as Industry
    }
  }

  return bestMatch
}
