import type { CVTheme, ThemeCategory, Industry, SidebarStyle } from './types/cv'

export interface ThemePreset extends CVTheme {
  id: string
  name: string
  category: ThemeCategory
  industry?: Industry
  description: string
}

// Industry-Focused Themes (10)
const industryThemes: ThemePreset[] = [
  {
    id: 'tech-modern',
    name: 'Tech Modern',
    category: 'industry',
    industry: 'tech',
    description: 'Clean tech startup feel with modern aesthetics',
    colors: {
      primary: '#0EA5E9',
      accent: '#22C55E',
      text: '#0F172A',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'finance',
    name: 'Finance',
    category: 'industry',
    industry: 'finance',
    description: 'Conservative banking style, trustworthy',
    colors: {
      primary: '#1E3A5F',
      accent: '#C9A227',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'bordered',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    category: 'industry',
    industry: 'healthcare',
    description: 'Clinical, clean, and trustworthy',
    colors: {
      primary: '#0891B2',
      accent: '#14B8A6',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'academic',
    skillsStyle: 'grid',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'legal',
    name: 'Legal',
    category: 'industry',
    industry: 'legal',
    description: 'Traditional, authoritative presence',
    colors: {
      primary: '#1C1917',
      accent: '#78350F',
      text: '#1C1917',
      background: '#FFFFFF',
      secondary: '#57534E',
    },
    fonts: { heading: 'Playfair Display', body: 'Merriweather' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'academia',
    name: 'Academia',
    category: 'industry',
    industry: 'academia',
    description: 'Academic and research focused',
    colors: {
      primary: '#7C3AED',
      accent: '#2563EB',
      text: '#1E1B4B',
      background: '#FFFFFF',
      secondary: '#6366F1',
    },
    fonts: { heading: 'Merriweather', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: true,
  },
  {
    id: 'creative-agency',
    name: 'Creative Agency',
    category: 'industry',
    industry: 'creative',
    description: 'Bold and artistic expression',
    colors: {
      primary: '#EC4899',
      accent: '#F59E0B',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#8B5CF6',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'engineering',
    name: 'Engineering',
    category: 'industry',
    industry: 'engineering',
    description: 'Technical, precise, and clean',
    colors: {
      primary: '#2563EB',
      accent: '#0EA5E9',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'marketing',
    name: 'Marketing',
    category: 'industry',
    industry: 'marketing',
    description: 'Dynamic and engaging',
    colors: {
      primary: '#F97316',
      accent: '#06B6D4',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#71717A',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'cards',
    educationStyle: 'compact',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'consulting',
    name: 'Consulting',
    category: 'industry',
    industry: 'consulting',
    description: 'Premium and polished',
    colors: {
      primary: '#0F172A',
      accent: '#3B82F6',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'disc',
    photoStyle: 'bordered',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'retail',
    name: 'Retail',
    category: 'industry',
    industry: 'retail',
    description: 'Friendly and approachable',
    colors: {
      primary: '#16A34A',
      accent: '#FBBF24',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
]

// Style-Focused Themes (10)
const styleThemes: ThemePreset[] = [
  {
    id: 'bold-modern',
    name: 'Bold Modern',
    category: 'style',
    description: 'Strong typography, high contrast',
    colors: {
      primary: '#000000',
      accent: '#FF0000',
      text: '#000000',
      background: '#FFFFFF',
      secondary: '#666666',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'square',
    photoStyle: 'square',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'soft-pastel',
    name: 'Soft Pastel',
    category: 'style',
    description: 'Gentle colors, rounded shapes',
    colors: {
      primary: '#8B5CF6',
      accent: '#F472B6',
      text: '#3F3F46',
      background: '#FAFAFA',
      secondary: '#A1A1AA',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'modern',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'cards',
    educationStyle: 'cards',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'none',
    sectionBorder: 'card',
    bulletStyle: 'circle',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    category: 'style',
    description: 'Black, white, and gray only',
    colors: {
      primary: '#18181B',
      accent: '#52525B',
      text: '#27272A',
      background: '#FFFFFF',
      secondary: '#71717A',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'minimal',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'dark-mode',
    name: 'Dark Mode',
    category: 'style',
    description: 'Dark background variant',
    colors: {
      primary: '#60A5FA',
      accent: '#34D399',
      text: '#F4F4F5',
      background: '#18181B',
      secondary: '#A1A1AA',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'gradient-accent',
    name: 'Gradient Accent',
    category: 'style',
    description: 'Gradient highlights throughout',
    colors: {
      primary: '#8B5CF6',
      accent: '#EC4899',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6366F1',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'gradient',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'neon',
    name: 'Neon',
    category: 'style',
    description: 'Bright accent colors that pop',
    colors: {
      primary: '#06B6D4',
      accent: '#F472B6',
      text: '#0F172A',
      background: '#FFFFFF',
      secondary: '#22D3EE',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'banner',
    experienceStyle: 'cards',
    educationStyle: 'cards',
    skillsStyle: 'chips',
    languagesStyle: 'pills',
    summaryStyle: 'boxed',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'vintage',
    name: 'Vintage',
    category: 'style',
    description: 'Retro classic feel',
    colors: {
      primary: '#78350F',
      accent: '#B45309',
      text: '#451A03',
      background: '#FEF3C7',
      secondary: '#92400E',
    },
    fonts: { heading: 'Playfair Display', body: 'Merriweather' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'quoted',
    sectionDivider: 'dotted',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'bordered',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'swiss',
    name: 'Swiss',
    category: 'style',
    description: 'Swiss design principles - clean grid',
    colors: {
      primary: '#EF4444',
      accent: '#000000',
      text: '#18181B',
      background: '#FFFFFF',
      secondary: '#71717A',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'square',
    photoStyle: 'none',
    dateFormat: 'numeric',
    showHeaderIcons: false,
  },
  {
    id: 'japanese-minimal',
    name: 'Japanese Minimal',
    category: 'style',
    description: 'Zen-inspired, whitespace-heavy',
    colors: {
      primary: '#1C1917',
      accent: '#DC2626',
      text: '#292524',
      background: '#FAFAF9',
      secondary: '#78716C',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'minimal',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'year-only',
    showHeaderIcons: false,
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    category: 'style',
    description: 'Raw, stark, impactful design',
    colors: {
      primary: '#000000',
      accent: '#FACC15',
      text: '#000000',
      background: '#FFFFFF',
      secondary: '#737373',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'modern',
    spacing: 'compact',
    headerStyle: 'left-aligned',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'tags-outlined',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'accent-left',
    bulletStyle: 'square',
    photoStyle: 'square',
    dateFormat: 'numeric',
    showHeaderIcons: false,
  },
]

// Specialty Themes (5+)
const specialtyThemes: ThemePreset[] = [
  {
    id: 'one-page',
    name: 'One Page',
    category: 'specialty',
    description: 'Optimized for single page',
    colors: {
      primary: '#374151',
      accent: '#6B7280',
      text: '#111827',
      background: '#FFFFFF',
      secondary: '#9CA3AF',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'compact',
    spacing: 'compact',
    headerStyle: 'compact',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'infographic',
    name: 'Infographic',
    category: 'specialty',
    description: 'Visual and chart emphasis',
    colors: {
      primary: '#3B82F6',
      accent: '#10B981',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6366F1',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'timeline',
    educationStyle: 'cards',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'timeline-focus',
    name: 'Timeline Focus',
    category: 'specialty',
    description: 'Timeline-centric design',
    colors: {
      primary: '#7C3AED',
      accent: '#A78BFA',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#8B5CF6',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'timeline',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'timeline',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'circle',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'photo-resume',
    name: 'Photo Resume',
    category: 'specialty',
    description: 'Large photo, visual emphasis',
    colors: {
      primary: '#0F172A',
      accent: '#38BDF8',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'sidebar-left',
    spacing: 'normal',
    headerStyle: 'photo-focus',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'federal',
    name: 'Federal',
    category: 'specialty',
    industry: 'government',
    description: 'Government and public sector',
    colors: {
      primary: '#1E3A8A',
      accent: '#1D4ED8',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'left-aligned',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'ats-optimized',
    name: 'ATS Optimized',
    category: 'specialty',
    description: 'Maximum ATS compatibility',
    colors: {
      primary: '#000000',
      accent: '#000000',
      text: '#000000',
      background: '#FFFFFF',
    },
    fonts: { heading: 'Arial', body: 'Arial' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
]

// Professional Color Themes (5 new premium templates)
const professionalThemes: ThemePreset[] = [
  {
    id: 'executive-navy',
    name: 'Executive Navy',
    category: 'style',
    industry: 'consulting',
    description: 'Premium dark navy with gold accents for C-level and consulting',
    colors: {
      primary: '#0F1729',
      accent: '#B8860B',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#475569',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'subtle',
    bulletStyle: 'square',
    photoStyle: 'bordered',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  {
    id: 'corporate-slate',
    name: 'Corporate Slate',
    category: 'style',
    industry: 'finance',
    description: 'Sophisticated slate gray for finance and banking',
    colors: {
      primary: '#334155',
      accent: '#6B82A6',
      text: '#1E293B',
      background: '#FFFFFF',
      secondary: '#64748B',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'inline',
    summaryStyle: 'boxed',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'classic-professional',
    name: 'Classic Professional',
    category: 'style',
    industry: 'legal',
    description: 'Traditional dark gray with burgundy for legal and formal',
    colors: {
      primary: '#1F2937',
      accent: '#722F37',
      text: '#1F2937',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Playfair Display', body: 'Merriweather' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'detailed',
    educationStyle: 'academic',
    skillsStyle: 'list',
    languagesStyle: 'grid',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'none',
    dateFormat: 'full',
    showHeaderIcons: false,
  },
  {
    id: 'modern-neutral',
    name: 'Modern Neutral',
    category: 'style',
    industry: 'general',
    description: 'Versatile neutral tones for any industry',
    colors: {
      primary: '#5C5C5C',
      accent: '#7D8471',
      text: '#333333',
      background: '#FFFFFF',
      secondary: '#9CA3AF',
    },
    fonts: { heading: 'DM Sans', body: 'Inter' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  {
    id: 'tech-minimal',
    name: 'Tech Minimal',
    category: 'style',
    industry: 'tech',
    description: 'Clean black and gray for tech and startups',
    colors: {
      primary: '#171717',
      accent: '#9CA3AF',
      text: '#171717',
      background: '#FFFFFF',
      secondary: '#6B7280',
    },
    fonts: { heading: 'Inter', body: 'Inter' },
    layout: 'minimal',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'compact',
    educationStyle: 'compact',
    skillsStyle: 'pills',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
]

// Combined theme presets
export const themePresets: ThemePreset[] = [
  ...industryThemes,
  ...styleThemes,
  ...specialtyThemes,
  ...professionalThemes,
]

// Legacy predefined themes (backwards compatible)
export const predefinedThemes: Record<string, CVTheme> = {
  ats: themePresets.find(t => t.id === 'ats-optimized')!,
  professional: {
    colors: {
      primary: '#3B82F6',
      accent: '#10B981',
      text: '#1F2937',
      background: '#FFFFFF',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'line',
    sectionBorder: 'none',
    bulletStyle: 'disc',
    photoStyle: 'circle',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  creative: {
    colors: {
      primary: '#8B5CF6',
      accent: '#EC4899',
      text: '#18181B',
      background: '#FFFFFF',
    },
    fonts: { heading: 'DM Sans', body: 'DM Sans' },
    layout: 'modern',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'cards',
    educationStyle: 'cards',
    skillsStyle: 'pills',
    languagesStyle: 'pills',
    summaryStyle: 'highlighted',
    sectionDivider: 'accent-bar',
    sectionBorder: 'card',
    bulletStyle: 'arrow',
    photoStyle: 'rounded',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
  minimal: {
    colors: {
      primary: '#374151',
      accent: '#6B7280',
      text: '#111827',
      background: '#FFFFFF',
    },
    fonts: { heading: 'Geist', body: 'Geist' },
    layout: 'minimal',
    spacing: 'normal',
    headerStyle: 'left-aligned',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'list',
    languagesStyle: 'inline',
    summaryStyle: 'plain',
    sectionDivider: 'none',
    sectionBorder: 'none',
    bulletStyle: 'dash',
    photoStyle: 'none',
    dateFormat: 'short',
    showHeaderIcons: false,
  },
  elegant: {
    colors: {
      primary: '#1E40AF',
      accent: '#059669',
      text: '#0F172A',
      background: '#FFFFFF',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'relaxed',
    headerStyle: 'centered',
    experienceStyle: 'classic',
    educationStyle: 'classic',
    skillsStyle: 'grid',
    languagesStyle: 'grid',
    summaryStyle: 'boxed',
    sectionDivider: 'dotted',
    sectionBorder: 'subtle',
    bulletStyle: 'circle',
    photoStyle: 'bordered',
    dateFormat: 'full',
    showHeaderIcons: true,
  },
  executive: {
    colors: {
      primary: '#0F172A',
      accent: '#D97706',
      text: '#1E293B',
      background: '#FFFFFF',
    },
    fonts: { heading: 'Playfair Display', body: 'Inter' },
    layout: 'classic',
    spacing: 'normal',
    headerStyle: 'split',
    experienceStyle: 'detailed',
    educationStyle: 'classic',
    skillsStyle: 'bars',
    languagesStyle: 'bars',
    summaryStyle: 'plain',
    sectionDivider: 'accent-bar',
    sectionBorder: 'none',
    bulletStyle: 'square',
    photoStyle: 'bordered',
    dateFormat: 'short',
    showHeaderIcons: true,
  },
}

// Font options
export const fontOptions = [
  'Arial',
  'Calibri',
  'DM Sans',
  'Geist',
  'Inter',
  'Roboto',
  'Open Sans',
  'Lato',
  'Merriweather',
  'Playfair Display',
  'Montserrat',
  'Poppins',
  'Source Sans Pro',
  'Nunito',
  'Work Sans',
]

// Layout options with metadata
export const layoutOptions: Array<{
  value: CVTheme['layout']
  label: string
  description: string
}> = [
  { value: 'classic', label: 'Classic', description: 'Traditional single-column layout' },
  { value: 'modern', label: 'Modern', description: 'Contemporary design with visual elements' },
  { value: 'minimal', label: 'Minimal', description: 'Clean and simple' },
  { value: 'two-column', label: 'Two Column', description: 'Sidebar with main content' },
  { value: 'sidebar-left', label: 'Sidebar Left', description: 'Left sidebar for skills/contact' },
  { value: 'sidebar-right', label: 'Sidebar Right', description: 'Right sidebar for skills/contact' },
  { value: 'top-banner', label: 'Top Banner', description: 'Full-width header banner' },
  { value: 'compact', label: 'Compact', description: 'Dense, single-page optimized' },
  { value: 'timeline', label: 'Timeline', description: 'Vertical timeline layout' },
  { value: 'magazine', label: 'Magazine', description: 'Multi-column editorial style' },
]

// Helper functions
export function getThemesByCategory(category: ThemeCategory): ThemePreset[] {
  return themePresets.filter(t => t.category === category)
}

export function getThemesByIndustry(industry: Industry): ThemePreset[] {
  return themePresets.filter(t => t.industry === industry)
}

export function getThemeById(id: string): ThemePreset | undefined {
  return themePresets.find(t => t.id === id)
}

export function suggestThemeForIndustry(industry: Industry): ThemePreset | undefined {
  return themePresets.find(t => t.industry === industry) || themePresets.find(t => t.id === 'tech-modern')
}

// Industry detection keywords for AI auto-suggest
export const industryKeywords: Record<Industry, string[]> = {
  tech: ['software', 'developer', 'engineer', 'programming', 'tech', 'startup', 'web', 'mobile', 'frontend', 'backend', 'fullstack', 'devops', 'cloud', 'ai', 'machine learning', 'data science'],
  finance: ['finance', 'banking', 'investment', 'accounting', 'financial', 'analyst', 'trader', 'portfolio', 'wealth', 'asset'],
  healthcare: ['healthcare', 'medical', 'nurse', 'doctor', 'clinical', 'hospital', 'patient', 'pharmaceutical', 'health'],
  legal: ['legal', 'lawyer', 'attorney', 'law', 'paralegal', 'counsel', 'litigation', 'compliance'],
  academia: ['professor', 'research', 'academic', 'university', 'phd', 'teaching', 'lecturer', 'scholar', 'postdoc'],
  creative: ['design', 'creative', 'art', 'graphic', 'ux', 'ui', 'animation', 'video', 'photography', 'illustration'],
  engineering: ['mechanical', 'electrical', 'civil', 'structural', 'manufacturing', 'industrial', 'automotive'],
  marketing: ['marketing', 'brand', 'digital marketing', 'seo', 'content', 'social media', 'advertising', 'pr', 'communications'],
  consulting: ['consultant', 'consulting', 'strategy', 'management', 'advisory', 'business'],
  retail: ['retail', 'sales', 'store', 'customer service', 'merchandising', 'e-commerce', 'shop'],
  government: ['government', 'federal', 'state', 'public sector', 'civil service', 'policy', 'administration'],
  general: [],
}

// Quick color presets for theme customizer (used in ColorsTab)
export const colorPresets = {
  primary: [
    '#2563eb', '#7c3aed', '#059669', '#dc2626', '#ea580c', '#0891b2', '#4f46e5', '#be185d', // Vibrant
    '#0F1729', '#334155', '#1F2937', '#5C5C5C', '#171717', '#1E3A5F', // Professional/muted
  ],
  accent: [
    '#3b82f6', '#8b5cf6', '#10b981', '#ef4444', '#f97316', '#06b6d4', '#6366f1', '#ec4899', // Vibrant
    '#B8860B', '#6B82A6', '#722F37', '#7D8471', '#9CA3AF', '#C9A227', // Professional/muted
  ],
  text: ['#0f172a', '#1e293b', '#334155', '#374151', '#1f2937', '#111827'],
  background: ['#ffffff', '#f8fafc', '#f1f5f9', '#fefce8', '#fef2f2', '#f0fdf4'],
}

export function detectIndustryFromText(text: string): Industry {
  const lowerText = text.toLowerCase()
  let bestMatch: Industry = 'general'
  let maxScore = 0

  for (const [industry, keywords] of Object.entries(industryKeywords)) {
    if (industry === 'general') continue
    const score = keywords.filter(kw => lowerText.includes(kw)).length
    if (score > maxScore) {
      maxScore = score
      bestMatch = industry as Industry
    }
  }

  return bestMatch
}
