import type { CVData } from '@/lib/types/cv'
import { getThemeById } from '@/lib/cv-themes'

// Helper to generate unique IDs
const id = () => Math.random().toString(36).substring(2, 9)

// Complete example CVs with full CVData format for real CV previews
// Interleaved: single-column (1-8) and two-column (9-16) layouts alternate
export const exampleCVs: Omit<CVData, 'id' | 'userId' | 'createdAt' | 'updatedAt'>[] = [
  // 1. Sarah Chen - ATS Optimized (Arial, no photo)
  {
    personalInfo: {
      fullName: 'Sarah Chen',
      email: 'sarah.chen@email.com',
      phone: '+1 (415) 555-0123',
      location: 'San Francisco, CA',
      linkedIn: 'linkedin.com/in/sarahchen',
    },
    summary: 'Results-driven marketing leader with 7+ years of experience scaling B2B SaaS brands. Led campaigns that drove 340% increase in qualified leads and $12M in pipeline revenue.',
    workExperience: [
      {
        id: id(),
        company: 'Spotify',
        position: 'Marketing Manager',
        startDate: '2021-03',
        endDate: '',
        current: true,
        location: 'San Francisco, CA',
        description: 'Lead a team of 8 marketers driving global brand campaigns.',
        achievements: [
          'Increased brand awareness by 45% through integrated marketing campaigns',
          'Managed $5M annual marketing budget with 120% ROI',
          'Launched 3 successful product campaigns reaching 50M+ users',
        ],
      },
      {
        id: id(),
        company: 'Dropbox',
        position: 'Senior Marketing Specialist',
        startDate: '2018-06',
        endDate: '2021-02',
        current: false,
        location: 'San Francisco, CA',
        description: 'Managed $2M annual budget for demand generation programs.',
        achievements: [
          'Drove 340% increase in qualified leads through content marketing',
          'Built and managed partner co-marketing program with 15 partners',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'UC Berkeley Haas',
        degree: 'MBA',
        field: 'Marketing',
        startDate: '2016-08',
        endDate: '2018-05',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Brand Strategy', category: 'Marketing', level: 'expert' },
      { id: id(), name: 'Google Analytics', category: 'Tools', level: 'expert' },
      { id: id(), name: 'Content Marketing', category: 'Marketing', level: 'expert' },
      { id: id(), name: 'SEO/SEM', category: 'Marketing', level: 'advanced' },
      { id: id(), name: 'Team Leadership', category: 'Soft Skills', level: 'expert' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'Mandarin', level: 'advanced' },
    ],
    certificates: [],
    theme: getThemeById('ats-optimized')!,
    footer: { rodoConsent: '' },
  },

  // 9. Olivia Martinez - Creative Agency (sidebar-left, DM Sans, with photo)
  {
    personalInfo: {
      fullName: 'Olivia Martinez',
      email: 'olivia.m@email.com',
      phone: '+1 (305) 555-0891',
      location: 'Miami, FL',
      linkedIn: 'linkedin.com/in/oliviamartinez',
      website: 'oliviamartinez.co',
      profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face',
    },
    summary: 'Creative director with 8+ years leading brand campaigns for global lifestyle brands. Expertise in digital storytelling and immersive brand experiences.',
    workExperience: [
      {
        id: id(),
        company: 'VaynerMedia',
        position: 'Creative Director',
        startDate: '2021-04',
        endDate: '',
        current: true,
        location: 'Miami, FL',
        description: 'Lead creative strategy for Fortune 100 consumer brands.',
        achievements: [
          'Directed campaigns generating 500M+ social impressions',
          'Won 3 Cannes Lions for digital innovation',
          'Built team of 15 creatives across 3 offices',
        ],
      },
      {
        id: id(),
        company: 'R/GA',
        position: 'Senior Art Director',
        startDate: '2018-01',
        endDate: '2021-03',
        current: false,
        location: 'New York, NY',
        description: 'Led visual design for Nike and Samsung campaigns.',
        achievements: [
          'Created viral campaign with 100M+ views',
          'Managed $3M production budgets',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'Parsons School of Design',
        degree: 'BFA',
        field: 'Communication Design',
        startDate: '2012-09',
        endDate: '2016-05',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Brand Strategy', category: 'Creative', level: 'expert' },
      { id: id(), name: 'Art Direction', category: 'Creative', level: 'expert' },
      { id: id(), name: 'Adobe Creative Suite', category: 'Tools', level: 'expert' },
      { id: id(), name: 'Video Production', category: 'Creative', level: 'advanced' },
      { id: id(), name: 'Team Leadership', category: 'Soft Skills', level: 'expert' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'Spanish', level: 'expert' },
    ],
    certificates: [],
    theme: {
      ...getThemeById('creative-agency')!,
      photoStyle: 'rounded',
      colors: {
        primary: '#C49595',
        accent: '#D8A4A8',
        text: '#3A3A3A',
        background: '#FFFFFF',
        secondary: '#8B7A7A',
      },
    },
    footer: { rodoConsent: '' },
  },

  // 2. Marcus Johnson - Tech Minimal (Inter, no photo)
  {
    personalInfo: {
      fullName: 'Marcus Johnson',
      email: 'marcus.j@email.com',
      phone: '+1 (512) 555-0456',
      location: 'Austin, TX',
      github: 'github.com/marcusj',
      linkedIn: 'linkedin.com/in/marcusjohnson',
    },
    summary: 'Full-stack engineer with 5 years of experience building scalable payment systems. Passionate about clean code, developer experience, and system reliability.',
    workExperience: [
      {
        id: id(),
        company: 'Stripe',
        position: 'Software Engineer',
        startDate: '2022-01',
        endDate: '',
        current: true,
        location: 'Austin, TX',
        description: 'Building core payment infrastructure serving millions of transactions.',
        achievements: [
          'Designed and implemented new payment processing pipeline handling $50M+ daily',
          'Reduced API latency by 40% through database optimization',
          'Mentored 3 junior engineers on best practices and code review',
        ],
      },
      {
        id: id(),
        company: 'Plaid',
        position: 'Backend Developer',
        startDate: '2019-06',
        endDate: '2021-12',
        current: false,
        location: 'San Francisco, CA',
        description: 'Developed APIs for financial data aggregation platform.',
        achievements: [
          'Built real-time transaction classification system with 98% accuracy',
          'Implemented OAuth 2.0 authentication for 200+ bank integrations',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'Georgia Tech',
        degree: 'B.S.',
        field: 'Computer Science',
        startDate: '2015-08',
        endDate: '2019-05',
        current: false,
        gpa: '3.8',
      },
    ],
    skills: [
      { id: id(), name: 'Python', category: 'Languages', level: 'expert' },
      { id: id(), name: 'Go', category: 'Languages', level: 'advanced' },
      { id: id(), name: 'PostgreSQL', category: 'Databases', level: 'expert' },
      { id: id(), name: 'AWS', category: 'Cloud', level: 'advanced' },
      { id: id(), name: 'Kubernetes', category: 'DevOps', level: 'intermediate' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
    ],
    certificates: [],
    theme: getThemeById('tech-minimal')!,
    footer: { rodoConsent: '' },
  },

  // 10. Alex Kim - Infographic (sidebar-left, DM Sans, with photo)
  {
    personalInfo: {
      fullName: 'Alex Kim',
      email: 'alex.kim@email.com',
      phone: '+1 (415) 555-0234',
      location: 'San Francisco, CA',
      linkedIn: 'linkedin.com/in/alexkim',
      github: 'github.com/alexkim',
      profileImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
    },
    summary: 'Data scientist specializing in ML/AI applications for fintech. Published researcher with expertise in predictive modeling and real-time fraud detection systems.',
    workExperience: [
      {
        id: id(),
        company: 'Square',
        position: 'Senior Data Scientist',
        startDate: '2022-02',
        endDate: '',
        current: true,
        location: 'San Francisco, CA',
        description: 'Lead ML initiatives for fraud detection platform.',
        achievements: [
          'Built ML model reducing fraud losses by $50M annually',
          'Deployed real-time scoring system processing 10K TPS',
          'Published 2 papers at NeurIPS on anomaly detection',
        ],
      },
      {
        id: id(),
        company: 'PayPal',
        position: 'Data Scientist',
        startDate: '2019-06',
        endDate: '2022-01',
        current: false,
        location: 'San Jose, CA',
        description: 'Developed credit risk models for merchant lending.',
        achievements: [
          'Improved default prediction accuracy by 25%',
          'Automated feature engineering pipeline',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'Stanford University',
        degree: 'M.S.',
        field: 'Computer Science (AI Track)',
        startDate: '2017-09',
        endDate: '2019-06',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Python/PyTorch', category: 'Technical', level: 'expert' },
      { id: id(), name: 'Machine Learning', category: 'Data Science', level: 'expert' },
      { id: id(), name: 'SQL/Spark', category: 'Data', level: 'expert' },
      { id: id(), name: 'MLOps', category: 'Engineering', level: 'advanced' },
      { id: id(), name: 'Statistical Modeling', category: 'Data Science', level: 'expert' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'Korean', level: 'advanced' },
    ],
    certificates: [],
    theme: {
      ...getThemeById('infographic')!,
      photoStyle: 'circle',
      colors: {
        primary: '#6CA9D8',
        accent: '#79BFE0',
        text: '#2D3F4F',
        background: '#FFFFFF',
        secondary: '#5B7E8F',
      },
    },
    footer: { rodoConsent: '' },
  },

  // 3. Emma Williams - Corporate Slate (Inter, with photo, no border)
  {
    personalInfo: {
      fullName: 'Emma Williams',
      email: 'emma.williams@email.com',
      phone: '+1 (212) 555-0789',
      location: 'New York, NY',
      linkedIn: 'linkedin.com/in/emmawilliams',
      profileImage: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face',
    },
    summary: 'CFA charterholder with expertise in equity research and financial modeling. Track record of identifying high-growth opportunities in the technology sector with 85% recommendation accuracy.',
    workExperience: [
      {
        id: id(),
        company: 'Goldman Sachs',
        position: 'Financial Analyst',
        startDate: '2021-07',
        endDate: '',
        current: true,
        location: 'New York, NY',
        description: 'Cover 15+ tech companies with combined market cap of $500B.',
        achievements: [
          'Published 50+ equity research reports with 85% accuracy on price targets',
          'Identified 3 undervalued stocks that outperformed S&P 500 by 40%',
          'Built proprietary DCF model adopted by entire tech coverage team',
        ],
      },
      {
        id: id(),
        company: 'Morgan Stanley',
        position: 'Junior Analyst',
        startDate: '2019-06',
        endDate: '2021-06',
        current: false,
        location: 'New York, NY',
        description: 'Built DCF models and conducted due diligence for M&A deals.',
        achievements: [
          'Supported $2B acquisition with comprehensive financial analysis',
          'Automated weekly reporting saving 10 hours per week',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'NYU Stern',
        degree: 'B.S.',
        field: 'Finance',
        startDate: '2015-09',
        endDate: '2019-05',
        current: false,
        gpa: '3.9',
      },
    ],
    skills: [
      { id: id(), name: 'Financial Modeling', category: 'Finance', level: 'expert' },
      { id: id(), name: 'Excel/VBA', category: 'Tools', level: 'expert' },
      { id: id(), name: 'Bloomberg Terminal', category: 'Tools', level: 'advanced' },
      { id: id(), name: 'Equity Research', category: 'Finance', level: 'expert' },
      { id: id(), name: 'Valuation', category: 'Finance', level: 'expert' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'French', level: 'intermediate' },
    ],
    certificates: [
      {
        id: id(),
        name: 'CFA Charter',
        issuer: 'CFA Institute',
        issueDate: '2021-09',
      },
    ],
    theme: { ...getThemeById('corporate-slate')!, photoStyle: 'circle' },
    footer: { rodoConsent: '' },
  },

  // 11. Rachel Thompson - Photo Resume (sidebar-left, DM Sans / Inter, with photo)
  {
    personalInfo: {
      fullName: 'Rachel Thompson',
      email: 'rachel.t@email.com',
      phone: '+1 (312) 555-0567',
      location: 'Chicago, IL',
      linkedIn: 'linkedin.com/in/rachelthompson',
      profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face',
    },
    summary: 'HR leader transforming talent acquisition for high-growth startups. Built recruiting engines that scaled teams from 50 to 500+ employees.',
    workExperience: [
      {
        id: id(),
        company: 'Figma',
        position: 'Head of Talent Acquisition',
        startDate: '2021-08',
        endDate: '',
        current: true,
        location: 'Chicago, IL (Remote)',
        description: 'Lead global recruiting strategy for 800+ person company.',
        achievements: [
          'Scaled team from 200 to 500 in 18 months',
          'Reduced time-to-hire by 40% through process optimization',
          'Achieved 95% offer acceptance rate',
        ],
      },
      {
        id: id(),
        company: 'Stripe',
        position: 'Senior Technical Recruiter',
        startDate: '2018-03',
        endDate: '2021-07',
        current: false,
        location: 'San Francisco, CA',
        description: 'Hired 100+ engineers for payments infrastructure teams.',
        achievements: [
          'Built university recruiting program with 15 target schools',
          'Pioneered skills-based assessment reducing bias by 30%',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'Northwestern University',
        degree: 'B.A.',
        field: 'Psychology',
        startDate: '2012-09',
        endDate: '2016-05',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Talent Strategy', category: 'HR', level: 'expert' },
      { id: id(), name: 'Executive Search', category: 'Recruiting', level: 'expert' },
      { id: id(), name: 'Employer Branding', category: 'HR', level: 'advanced' },
      { id: id(), name: 'Greenhouse/Lever', category: 'Tools', level: 'expert' },
      { id: id(), name: 'DEI Initiatives', category: 'HR', level: 'advanced' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
    ],
    certificates: [],
    theme: {
      ...getThemeById('photo-resume')!,
      photoStyle: 'rounded',
      colors: {
        primary: '#7FAC7F',
        accent: '#88C8B8',
        text: '#2D3F2D',
        background: '#FFFFFF',
        secondary: '#5B7E5B',
      },
    },
    footer: { rodoConsent: '' },
  },

  // 4. David Rodriguez - Monochrome (Inter, no photo)
  {
    personalInfo: {
      fullName: 'David Rodriguez',
      email: 'david.r@email.com',
      phone: '+1 (206) 555-0321',
      location: 'Seattle, WA',
      linkedIn: 'linkedin.com/in/davidrodriguez',
    },
    summary: 'Human-centered researcher who transforms user insights into product strategy. Led research initiatives that increased user retention by 45% and reduced churn by 30%.',
    workExperience: [
      {
        id: id(),
        company: 'Airbnb',
        position: 'Senior UX Researcher',
        startDate: '2020-08',
        endDate: '',
        current: true,
        location: 'Seattle, WA',
        description: 'Lead research for Experiences product, 50M+ users globally.',
        achievements: [
          'Conducted 150+ user interviews informing product roadmap',
          'Increased booking conversion by 25% through research-driven redesign',
          'Built research ops framework adopted across 5 product teams',
        ],
      },
      {
        id: id(),
        company: 'Microsoft',
        position: 'UX Researcher',
        startDate: '2017-06',
        endDate: '2020-07',
        current: false,
        location: 'Redmond, WA',
        description: 'Conducted 200+ user studies for Office 365 products.',
        achievements: [
          'Led usability studies that improved task completion by 35%',
          'Developed quantitative research methodology for A/B testing',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'Carnegie Mellon',
        degree: 'M.S.',
        field: 'Human-Computer Interaction',
        startDate: '2015-08',
        endDate: '2017-05',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'User Interviews', category: 'Research', level: 'expert' },
      { id: id(), name: 'Usability Testing', category: 'Research', level: 'expert' },
      { id: id(), name: 'Survey Design', category: 'Research', level: 'advanced' },
      { id: id(), name: 'Figma', category: 'Tools', level: 'advanced' },
      { id: id(), name: 'Data Analysis', category: 'Analysis', level: 'advanced' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'Spanish', level: 'advanced' },
    ],
    certificates: [],
    theme: getThemeById('monochrome')!,
    footer: { rodoConsent: '' },
  },

  // 12. Jordan Patel - Neon (modern cards, Inter, no photo)
  {
    personalInfo: {
      fullName: 'Jordan Patel',
      email: 'jordan.patel@email.com',
      phone: '+1 (213) 555-0789',
      location: 'Los Angeles, CA',
      linkedIn: 'linkedin.com/in/jordanpatel',
      github: 'github.com/jpatel',
    },
    summary: 'DevOps engineer automating infrastructure at scale. Kubernetes expert with track record of 99.99% uptime for mission-critical systems.',
    workExperience: [
      {
        id: id(),
        company: 'Netflix',
        position: 'Senior DevOps Engineer',
        startDate: '2022-01',
        endDate: '',
        current: true,
        location: 'Los Angeles, CA',
        description: 'Manage infrastructure serving 200M+ subscribers globally.',
        achievements: [
          'Reduced deployment time from 2 hours to 10 minutes',
          'Built self-healing infrastructure saving $2M annually',
          'Maintained 99.99% uptime during 3x traffic spikes',
        ],
      },
      {
        id: id(),
        company: 'Twilio',
        position: 'DevOps Engineer',
        startDate: '2019-05',
        endDate: '2021-12',
        current: false,
        location: 'San Francisco, CA',
        description: 'Automated cloud infrastructure for communications platform.',
        achievements: [
          'Migrated 500+ services to Kubernetes',
          'Implemented GitOps reducing config drift by 90%',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'UCLA',
        degree: 'B.S.',
        field: 'Computer Science',
        startDate: '2015-09',
        endDate: '2019-06',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Kubernetes', category: 'Infrastructure', level: 'expert' },
      { id: id(), name: 'Terraform', category: 'IaC', level: 'expert' },
      { id: id(), name: 'AWS/GCP', category: 'Cloud', level: 'expert' },
      { id: id(), name: 'CI/CD', category: 'DevOps', level: 'expert' },
      { id: id(), name: 'Python/Go', category: 'Languages', level: 'advanced' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
    ],
    certificates: [],
    theme: {
      ...getThemeById('neon')!,
      colors: {
        primary: '#78C8B0',
        accent: '#6EB8D3',
        text: '#2D4A4A',
        background: '#FFFFFF',
        secondary: '#5B8E8E',
      },
    },
    footer: { rodoConsent: '' },
  },

  // 5. Lisa Park - Modern Neutral (DM Sans / Inter, with photo, no border)
  {
    personalInfo: {
      fullName: 'Lisa Park',
      email: 'lisa.park@email.com',
      phone: '+1 (323) 555-0654',
      location: 'Los Angeles, CA',
      linkedIn: 'linkedin.com/in/lisapark',
      profileImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    },
    summary: 'Award-winning designer creating visual identities for Fortune 500 brands. Featured in Communication Arts and AIGA annual. Passionate about typography and brand storytelling.',
    workExperience: [
      {
        id: id(),
        company: 'Adobe',
        position: 'Senior Graphic Designer',
        startDate: '2021-02',
        endDate: '',
        current: true,
        location: 'Los Angeles, CA',
        description: 'Design lead for Creative Cloud marketing materials.',
        achievements: [
          'Led visual design for Adobe MAX conference reaching 200K+ attendees',
          'Created brand guidelines adopted by 15 global marketing teams',
          'Won Adobe internal design award for campaign excellence',
        ],
      },
      {
        id: id(),
        company: 'Pentagram',
        position: 'Graphic Designer',
        startDate: '2018-06',
        endDate: '2021-01',
        current: false,
        location: 'New York, NY',
        description: 'Created brand systems for Nike, Spotify, and Citibank.',
        achievements: [
          'Designed logo systems for 10+ Fortune 500 clients',
          'Featured in Communication Arts Design Annual 2020',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'RISD',
        degree: 'BFA',
        field: 'Graphic Design',
        startDate: '2014-09',
        endDate: '2018-05',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Adobe Creative Suite', category: 'Tools', level: 'expert' },
      { id: id(), name: 'Figma', category: 'Tools', level: 'expert' },
      { id: id(), name: 'Brand Identity', category: 'Design', level: 'expert' },
      { id: id(), name: 'Typography', category: 'Design', level: 'expert' },
      { id: id(), name: 'Motion Graphics', category: 'Design', level: 'advanced' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'Korean', level: 'advanced' },
    ],
    certificates: [],
    theme: { ...getThemeById('modern-neutral')!, photoStyle: 'circle' },
    footer: { rodoConsent: '' },
  },

  // 13. Sophie Chen - Gradient Accent (modern, DM Sans / Inter, with photo)
  {
    personalInfo: {
      fullName: 'Sophie Chen',
      email: 'sophie.chen@email.com',
      phone: '+1 (617) 555-0345',
      location: 'Boston, MA',
      linkedIn: 'linkedin.com/in/sophiechen',
      profileImage: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face',
    },
    summary: 'Product designer crafting delightful B2B experiences. Passionate about design systems and accessibility-first design that scales.',
    workExperience: [
      {
        id: id(),
        company: 'HubSpot',
        position: 'Senior Product Designer',
        startDate: '2021-06',
        endDate: '',
        current: true,
        location: 'Boston, MA',
        description: 'Design lead for CRM product serving 150K+ customers.',
        achievements: [
          'Redesigned core workflows increasing user satisfaction by 35%',
          'Built design system used by 50+ designers globally',
          'Led accessibility audit achieving WCAG 2.1 AA compliance',
        ],
      },
      {
        id: id(),
        company: 'Mailchimp',
        position: 'Product Designer',
        startDate: '2018-08',
        endDate: '2021-05',
        current: false,
        location: 'Atlanta, GA',
        description: 'Designed email campaign builder and analytics dashboard.',
        achievements: [
          'Increased email builder engagement by 50%',
          'Shipped redesigned mobile app with 4.8 star rating',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'MIT',
        degree: 'B.S.',
        field: 'Design',
        startDate: '2014-09',
        endDate: '2018-05',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Figma', category: 'Tools', level: 'expert' },
      { id: id(), name: 'Design Systems', category: 'Design', level: 'expert' },
      { id: id(), name: 'Prototyping', category: 'Design', level: 'expert' },
      { id: id(), name: 'User Research', category: 'Research', level: 'advanced' },
      { id: id(), name: 'Accessibility', category: 'Design', level: 'advanced' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'Mandarin', level: 'advanced' },
    ],
    certificates: [],
    theme: {
      ...getThemeById('gradient-accent')!,
      photoStyle: 'rounded',
      colors: {
        primary: '#A899B9',
        accent: '#B892B8',
        text: '#3A3A4A',
        background: '#FFFFFF',
        secondary: '#7B7B8B',
      },
    },
    footer: { rodoConsent: '' },
  },

  // 6. James Miller - One Page (Inter, no photo)
  {
    personalInfo: {
      fullName: 'James Miller',
      email: 'james.miller@email.com',
      phone: '+1 (415) 555-0987',
      location: 'San Francisco, CA',
      linkedIn: 'linkedin.com/in/jamesmiller',
    },
    summary: 'Product leader who shipped features used by 10M+ users. Expert in 0-to-1 products, data-driven decision making, and cross-functional team leadership.',
    workExperience: [
      {
        id: id(),
        company: 'Notion',
        position: 'Senior Product Manager',
        startDate: '2022-03',
        endDate: '',
        current: true,
        location: 'San Francisco, CA',
        description: 'Own collaboration features with 25% of total DAU.',
        achievements: [
          'Launched real-time collaboration used by 5M+ monthly active users',
          'Increased feature adoption by 60% through onboarding redesign',
          'Led cross-functional team of 12 engineers and 3 designers',
        ],
      },
      {
        id: id(),
        company: 'Slack',
        position: 'Product Manager',
        startDate: '2019-08',
        endDate: '2022-02',
        current: false,
        location: 'San Francisco, CA',
        description: 'Launched Huddles feature, now used by 5M+ daily.',
        achievements: [
          'Shipped Huddles from 0-to-1, now 20% of daily engagement',
          'Drove 35% increase in team workspace creation through onboarding',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'Stanford GSB',
        degree: 'MBA',
        field: 'Business Administration',
        startDate: '2017-09',
        endDate: '2019-06',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Product Strategy', category: 'Product', level: 'expert' },
      { id: id(), name: 'Roadmapping', category: 'Product', level: 'expert' },
      { id: id(), name: 'A/B Testing', category: 'Analytics', level: 'advanced' },
      { id: id(), name: 'SQL', category: 'Technical', level: 'advanced' },
      { id: id(), name: 'Agile/Scrum', category: 'Process', level: 'expert' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
    ],
    certificates: [],
    theme: getThemeById('one-page')!,
    footer: { rodoConsent: '' },
  },

  // 14. Tyler Jackson - Soft Pastel (modern cards, DM Sans, no photo)
  {
    personalInfo: {
      fullName: 'Tyler Jackson',
      email: 'tyler.j@email.com',
      phone: '+1 (503) 555-0678',
      location: 'Portland, OR',
      linkedIn: 'linkedin.com/in/tylerjackson',
    },
    summary: 'Sustainability consultant helping Fortune 500 companies achieve net-zero goals. Expert in carbon accounting and ESG strategy implementation.',
    workExperience: [
      {
        id: id(),
        company: 'McKinsey & Company',
        position: 'Senior Consultant, Sustainability Practice',
        startDate: '2021-03',
        endDate: '',
        current: true,
        location: 'Portland, OR',
        description: 'Lead sustainability transformation for global enterprises.',
        achievements: [
          'Developed net-zero roadmaps for 5 Fortune 100 clients',
          'Identified $200M in cost savings through energy efficiency',
          'Published thought leadership on circular economy',
        ],
      },
      {
        id: id(),
        company: 'Patagonia',
        position: 'Environmental Analyst',
        startDate: '2018-06',
        endDate: '2021-02',
        current: false,
        location: 'Ventura, CA',
        description: 'Managed carbon footprint analysis and reporting.',
        achievements: [
          'Reduced supply chain emissions by 30%',
          'Built supplier sustainability scorecard',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'Yale School of the Environment',
        degree: 'M.E.M.',
        field: 'Environmental Management',
        startDate: '2016-09',
        endDate: '2018-05',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Carbon Accounting', category: 'Sustainability', level: 'expert' },
      { id: id(), name: 'ESG Strategy', category: 'Consulting', level: 'expert' },
      { id: id(), name: 'Life Cycle Assessment', category: 'Analysis', level: 'advanced' },
      { id: id(), name: 'Stakeholder Management', category: 'Soft Skills', level: 'expert' },
      { id: id(), name: 'Data Visualization', category: 'Tools', level: 'advanced' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
    ],
    certificates: [],
    theme: {
      ...getThemeById('soft-pastel')!,
      colors: {
        primary: '#98C8A9',
        accent: '#A8D0C2',
        text: '#3A4A3A',
        background: '#FAFAFA',
        secondary: '#7B8B7B',
      },
    },
    footer: { rodoConsent: '' },
  },

  // 7. Kevin Lee - Consulting (Playfair Display / Inter, with photo, no border)
  {
    personalInfo: {
      fullName: 'Kevin Lee',
      email: 'kevin.lee@email.com',
      phone: '+1 (Remote)',
      location: 'Remote',
      github: 'github.com/kevinlee',
      linkedIn: 'linkedin.com/in/kevinlee',
      profileImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face',
    },
    summary: 'Frontend specialist obsessed with performance and DX. Core contributor to popular open-source UI libraries. Building the future of web development tooling.',
    workExperience: [
      {
        id: id(),
        company: 'Vercel',
        position: 'Senior Frontend Engineer',
        startDate: '2022-06',
        endDate: '',
        current: true,
        location: 'Remote',
        description: 'Building the future of web development tooling.',
        achievements: [
          'Core maintainer of Next.js with 100K+ GitHub stars',
          'Reduced bundle size by 40% through tree-shaking improvements',
          'Built incremental static regeneration feature used by 500K+ sites',
        ],
      },
      {
        id: id(),
        company: 'Shopify',
        position: 'Frontend Engineer',
        startDate: '2019-09',
        endDate: '2022-05',
        current: false,
        location: 'Toronto, Canada',
        description: 'Built checkout experiences processing $10B+ annually.',
        achievements: [
          'Optimized checkout flow reducing abandonment by 15%',
          'Led migration to React 18 concurrent features',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'University of Waterloo',
        degree: 'B.S.',
        field: 'Computer Science',
        startDate: '2015-09',
        endDate: '2019-04',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'React', category: 'Frontend', level: 'expert' },
      { id: id(), name: 'TypeScript', category: 'Languages', level: 'expert' },
      { id: id(), name: 'Next.js', category: 'Frameworks', level: 'expert' },
      { id: id(), name: 'Tailwind CSS', category: 'Styling', level: 'expert' },
      { id: id(), name: 'GraphQL', category: 'APIs', level: 'advanced' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'Korean', level: 'intermediate' },
    ],
    certificates: [],
    theme: { ...getThemeById('consulting')!, photoStyle: 'circle' },
    footer: { rodoConsent: '' },
  },

  // 15. Maya Singh - Marketing (modern banner, DM Sans / Inter, with photo)
  {
    personalInfo: {
      fullName: 'Maya Singh',
      email: 'maya.singh@email.com',
      phone: '+1 (512) 555-0901',
      location: 'Austin, TX',
      linkedIn: 'linkedin.com/in/mayasingh',
      website: 'mayasingh.io',
      profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face',
    },
    summary: 'Growth marketing leader scaling SaaS products from seed to Series C. Data-driven strategist with expertise in PLG and performance marketing.',
    workExperience: [
      {
        id: id(),
        company: 'Canva',
        position: 'Head of Growth Marketing',
        startDate: '2022-01',
        endDate: '',
        current: true,
        location: 'Austin, TX (Remote)',
        description: 'Lead growth initiatives for 100M+ monthly active users.',
        achievements: [
          'Grew monthly signups by 200% through viral loops',
          'Optimized CAC by 45% through channel mix modeling',
          'Launched referral program driving 30% of new users',
        ],
      },
      {
        id: id(),
        company: 'Calendly',
        position: 'Senior Growth Manager',
        startDate: '2019-04',
        endDate: '2021-12',
        current: false,
        location: 'Atlanta, GA',
        description: 'Scaled user acquisition from 5M to 15M users.',
        achievements: [
          'Built self-serve onboarding increasing activation by 60%',
          'Managed $10M annual paid media budget',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'University of Texas',
        degree: 'B.B.A.',
        field: 'Marketing',
        startDate: '2013-09',
        endDate: '2017-05',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Growth Strategy', category: 'Marketing', level: 'expert' },
      { id: id(), name: 'Performance Marketing', category: 'Marketing', level: 'expert' },
      { id: id(), name: 'Analytics/Amplitude', category: 'Tools', level: 'expert' },
      { id: id(), name: 'A/B Testing', category: 'Experimentation', level: 'advanced' },
      { id: id(), name: 'SQL', category: 'Technical', level: 'advanced' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'Hindi', level: 'advanced' },
    ],
    certificates: [],
    theme: {
      ...getThemeById('marketing')!,
      photoStyle: 'circle',
      colors: {
        primary: '#EF9B81',
        accent: '#EFA597',
        text: '#4A3A3A',
        background: '#FFFFFF',
        secondary: '#8B7B7B',
      },
    },
    footer: { rodoConsent: '' },
  },

  // 8. Michael Brown - Classic Professional (Playfair Display / Merriweather, no photo)
  {
    personalInfo: {
      fullName: 'Michael Brown',
      email: 'michael.brown@email.com',
      phone: '+1 (202) 555-0246',
      location: 'Washington, DC',
      linkedIn: 'linkedin.com/in/michaelbrown',
    },
    summary: 'Corporate attorney with 10+ years advising on M&A, securities, and governance. Closed $15B+ in transactions for Fortune 500 clients and PE firms.',
    workExperience: [
      {
        id: id(),
        company: 'Latham & Watkins',
        position: 'Senior Associate',
        startDate: '2019-01',
        endDate: '',
        current: true,
        location: 'Washington, DC',
        description: 'Lead counsel on cross-border M&A deals up to $2B.',
        achievements: [
          'Led legal team for $2B cross-border acquisition',
          'Advised on $5B IPO for major tech company',
          'Managed due diligence for 20+ transactions annually',
        ],
      },
      {
        id: id(),
        company: 'Skadden Arps',
        position: 'Associate',
        startDate: '2014-09',
        endDate: '2018-12',
        current: false,
        location: 'New York, NY',
        description: 'Advised Fortune 500 clients on SEC compliance.',
        achievements: [
          'Drafted SEC filings for 15+ public offerings',
          'Supported $8B merger with comprehensive regulatory analysis',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'Harvard Law School',
        degree: 'J.D.',
        field: 'Law',
        startDate: '2011-09',
        endDate: '2014-05',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'M&A', category: 'Legal', level: 'expert' },
      { id: id(), name: 'Securities Law', category: 'Legal', level: 'expert' },
      { id: id(), name: 'Corporate Governance', category: 'Legal', level: 'expert' },
      { id: id(), name: 'Due Diligence', category: 'Legal', level: 'expert' },
      { id: id(), name: 'Contract Negotiation', category: 'Legal', level: 'expert' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'German', level: 'intermediate' },
    ],
    certificates: [
      {
        id: id(),
        name: 'New York Bar',
        issuer: 'NY State Bar Association',
        issueDate: '2014-11',
      },
    ],
    theme: getThemeById('classic-professional')!,
    footer: { rodoConsent: '' },
  },

  // 16. Chris Nakamura - Tech Modern (modern, Inter, no photo)
  {
    personalInfo: {
      fullName: 'Chris Nakamura',
      email: 'chris.n@email.com',
      phone: '+1 (206) 555-0234',
      location: 'Seattle, WA',
      linkedIn: 'linkedin.com/in/chrisnakamura',
      github: 'github.com/cnakamura',
    },
    summary: 'Security engineer building zero-trust architectures for cloud-native applications. Bug bounty hunter with $100K+ in disclosed vulnerabilities.',
    workExperience: [
      {
        id: id(),
        company: 'Cloudflare',
        position: 'Senior Security Engineer',
        startDate: '2022-03',
        endDate: '',
        current: true,
        location: 'Seattle, WA',
        description: 'Secure infrastructure protecting 25M+ internet properties.',
        achievements: [
          'Designed zero-trust architecture for internal systems',
          'Led incident response for 3 critical vulnerabilities',
          'Built automated security scanning in CI/CD pipeline',
        ],
      },
      {
        id: id(),
        company: 'GitHub',
        position: 'Security Engineer',
        startDate: '2019-08',
        endDate: '2022-02',
        current: false,
        location: 'San Francisco, CA',
        description: 'Protected platform serving 100M+ developers.',
        achievements: [
          'Discovered and patched critical SSRF vulnerability',
          'Implemented secrets scanning detecting 10K+ exposed credentials',
        ],
      },
    ],
    education: [
      {
        id: id(),
        institution: 'University of Washington',
        degree: 'B.S.',
        field: 'Computer Science',
        startDate: '2015-09',
        endDate: '2019-06',
        current: false,
      },
    ],
    skills: [
      { id: id(), name: 'Penetration Testing', category: 'Security', level: 'expert' },
      { id: id(), name: 'Cloud Security', category: 'Security', level: 'expert' },
      { id: id(), name: 'Python/Rust', category: 'Languages', level: 'advanced' },
      { id: id(), name: 'Threat Modeling', category: 'Security', level: 'expert' },
      { id: id(), name: 'Incident Response', category: 'Security', level: 'advanced' },
    ],
    languages: [
      { id: id(), name: 'English', level: 'expert' },
      { id: id(), name: 'Japanese', level: 'intermediate' },
    ],
    certificates: [],
    theme: {
      ...getThemeById('tech-modern')!,
      colors: {
        primary: '#77BEDB',
        accent: '#A0D0D6',
        text: '#2D3F4F',
        background: '#FFFFFF',
        secondary: '#5B7E8F',
      },
    },
    footer: { rodoConsent: '' },
  },
]
